[build]
builder = "nixpacks"

[deploy]
startCommand = "python -c 'import uvicorn; print(\"uvicorn found\")' && python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 