[build]
builder = "dockerfile"

[deploy]
# Use our Python script to handle PORT correctly
startCommand = "python start_server.py"
# Re-enable health check now that app is working
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 