[build]
builder = "dockerfile"

[deploy]
# Use our Python script to handle PORT correctly
startCommand = "python start_server.py"
# Temporarily disable health check to avoid timeout issues
# healthcheckPath = "/api/health"
# healthcheckTimeout = 600
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 