[build]
builder = "dockerfile"

[deploy]
# Temporarily disable health check to avoid timeout issues
# healthcheckPath = "/api/health"
# healthcheckTimeout = 600
restartPolicyType = "on_failure"

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1" 